package com.oauth2.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of App.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class App implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** name. */
	private String name;

	/** appid. */
	private String appid;

	/** secret. */
	private String secret;

	/** domain. */
	private String domain;

	/** ban. */
	private String ban;

	/** create_at. */
	private Date createAt;

	/** update_at. */
	private Date updateAt;

	/**
	 * Constructor.
	 */
	public App() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the name.
	 * 
	 * @param name
	 *            name
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * Get the name.
	 * 
	 * @return name
	 */
	public String getName() {
		return this.name;
	}

	/**
	 * Set the appid.
	 * 
	 * @param appid
	 *            appid
	 */
	public void setAppid(String appid) {
		this.appid = appid;
	}

	/**
	 * Get the appid.
	 * 
	 * @return appid
	 */
	public String getAppid() {
		return this.appid;
	}

	/**
	 * Set the secret.
	 * 
	 * @param secret
	 *            secret
	 */
	public void setSecret(String secret) {
		this.secret = secret;
	}

	/**
	 * Get the secret.
	 * 
	 * @return secret
	 */
	public String getSecret() {
		return this.secret;
	}

	/**
	 * Set the domain.
	 * 
	 * @param domain
	 *            domain
	 */
	public void setDomain(String domain) {
		this.domain = domain;
	}

	/**
	 * Get the domain.
	 * 
	 * @return domain
	 */
	public String getDomain() {
		return this.domain;
	}

	/**
	 * Set the ban.
	 * 
	 * @param ban
	 *            ban
	 */
	public void setBan(String ban) {
		this.ban = ban;
	}

	/**
	 * Get the ban.
	 * 
	 * @return ban
	 */
	public String getBan() {
		return this.ban;
	}

	/**
	 * Set the create_at.
	 * 
	 * @param createAt
	 *            create_at
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * Get the create_at.
	 * 
	 * @return create_at
	 */
	public Date getCreateAt() {
		return this.createAt;
	}

	/**
	 * Set the update_at.
	 * 
	 * @param updateAt
	 *            update_at
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * Get the update_at.
	 * 
	 * @return update_at
	 */
	public Date getUpdateAt() {
		return this.updateAt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		App other = (App) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
