package com.oauth2.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of Token.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class Token implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** username. */
	private String username;

	/** appid. */
	private String appid;

	/** redirect_uri. */
	private String redirectUri;

	/** authorization_code. */
	private String authorizationCode;

	/** access_token. */
	private String accessToken;

	/** used. */
	private String used;

	/** create_at. */
	private Date createAt;

	/** update_at. */
	private Date updateAt;

	/**
	 * Constructor.
	 */
	public Token() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the username.
	 * 
	 * @param username
	 *            username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the username.
	 * 
	 * @return username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the appid.
	 * 
	 * @param appid
	 *            appid
	 */
	public void setAppid(String appid) {
		this.appid = appid;
	}

	/**
	 * Get the appid.
	 * 
	 * @return appid
	 */
	public String getAppid() {
		return this.appid;
	}

	/**
	 * Set the redirect_uri.
	 * 
	 * @param redirectUri
	 *            redirect_uri
	 */
	public void setRedirectUri(String redirectUri) {
		this.redirectUri = redirectUri;
	}

	/**
	 * Get the redirect_uri.
	 * 
	 * @return redirect_uri
	 */
	public String getRedirectUri() {
		return this.redirectUri;
	}

	/**
	 * Set the authorization_code.
	 * 
	 * @param authorizationCode
	 *            authorization_code
	 */
	public void setAuthorizationCode(String authorizationCode) {
		this.authorizationCode = authorizationCode;
	}

	/**
	 * Get the authorization_code.
	 * 
	 * @return authorization_code
	 */
	public String getAuthorizationCode() {
		return this.authorizationCode;
	}

	/**
	 * Set the access_token.
	 * 
	 * @param accessToken
	 *            access_token
	 */
	public void setAccessToken(String accessToken) {
		this.accessToken = accessToken;
	}

	/**
	 * Get the access_token.
	 * 
	 * @return access_token
	 */
	public String getAccessToken() {
		return this.accessToken;
	}

	/**
	 * Set the used.
	 * 
	 * @param used
	 *            used
	 */
	public void setUsed(String used) {
		this.used = used;
	}

	/**
	 * Get the used.
	 * 
	 * @return used
	 */
	public String getUsed() {
		return this.used;
	}

	/**
	 * Set the create_at.
	 * 
	 * @param createAt
	 *            create_at
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * Get the create_at.
	 * 
	 * @return create_at
	 */
	public Date getCreateAt() {
		return this.createAt;
	}

	/**
	 * Set the update_at.
	 * 
	 * @param updateAt
	 *            update_at
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * Get the update_at.
	 * 
	 * @return update_at
	 */
	public Date getUpdateAt() {
		return this.updateAt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		Token other = (Token) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
