package com.oauth2.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Model class of User.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** id. */
	private Integer id;

	/** username. */
	private String username;

	/** password. */
	private String password;

	/** realname. */
	private String realname;

	/** phone. */
	private String phone;

	/** create_at. */
	private Date createAt;

	/** update_at. */
	private Date updateAt;

	/** delete_at. */
	private Date deleteAt;

	/**
	 * Constructor.
	 */
	public User() {
	}

	/**
	 * Set the id.
	 * 
	 * @param id
	 *            id
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * Get the id.
	 * 
	 * @return id
	 */
	public Integer getId() {
		return this.id;
	}

	/**
	 * Set the username.
	 * 
	 * @param username
	 *            username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * Get the username.
	 * 
	 * @return username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * Set the password.
	 * 
	 * @param password
	 *            password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * Get the password.
	 * 
	 * @return password
	 */
	public String getPassword() {
		return this.password;
	}

	/**
	 * Set the realname.
	 * 
	 * @param realname
	 *            realname
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * Get the realname.
	 * 
	 * @return realname
	 */
	public String getRealname() {
		return this.realname;
	}

	/**
	 * Set the phone.
	 * 
	 * @param phone
	 *            phone
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * Get the phone.
	 * 
	 * @return phone
	 */
	public String getPhone() {
		return this.phone;
	}

	/**
	 * Set the create_at.
	 * 
	 * @param createAt
	 *            create_at
	 */
	public void setCreateAt(Date createAt) {
		this.createAt = createAt;
	}

	/**
	 * Get the create_at.
	 * 
	 * @return create_at
	 */
	public Date getCreateAt() {
		return this.createAt;
	}

	/**
	 * Set the update_at.
	 * 
	 * @param updateAt
	 *            update_at
	 */
	public void setUpdateAt(Date updateAt) {
		this.updateAt = updateAt;
	}

	/**
	 * Get the update_at.
	 * 
	 * @return update_at
	 */
	public Date getUpdateAt() {
		return this.updateAt;
	}

	/**
	 * Set the delete_at.
	 * 
	 * @param deleteAt
	 *            delete_at
	 */
	public void setDeleteAt(Date deleteAt) {
		this.deleteAt = deleteAt;
	}

	/**
	 * Get the delete_at.
	 * 
	 * @return delete_at
	 */
	public Date getDeleteAt() {
		return this.deleteAt;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (id == null) {
			if (other.id != null) {
				return false;
			}
		} else if (!id.equals(other.id)) {
			return false;
		}
		return true;
	}

}
